name: DevInfra

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  breaking-changes-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: angular/dev-infra/github-actions/breaking-changes-label@c4dabf8c1e204836079e81f39da2326cd8d848a4
        with:
          angular-robot-key: ${{ secrets.ANGULAR_ROBOT_PRIVATE_KEY }}
